name: flutter_galaxy
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  firebase_database: ^10.0.14
  firebase_core: ^2.7.0
  flutter_bloc: ^8.1.2
  flame: ^1.6.0
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass